name: Build
on: [pull_request, push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: akerl/action-checkout@v2.0.0
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Install shellcheck
      run: sudo apt install -y shellcheck
    - name: Install rubocop
      run: sudo gem install --no-user-install --no-document rubocop goodcop
    - name: Shellcheck
      run: 'shellcheck *.sh'
    - name: Rubocop
      run: rubocop -D
    - name: Notify on success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: akerl/github-action-slack-notify-build@v1.1.1
      with:
        channel_id: ${{ secrets.SLACK_BOT_CHANNEL }}
        status: success
        color: good
    - name: Notify on failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: akerl/github-action-slack-notify-build@v1.1.1
      with:
        channel_id: ${{ secrets.SLACK_BOT_CHANNEL }}
        status: failed
        color: danger

